In [119]:
%config Completer.use_jedi = False
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
import warnings
warnings.filterwarnings('ignore')
import random

%matplotlib inline

In [120]:
df = pd.read_excel("../Churn.xlsx")
print(df.shape)
df.head()

(7043, 12)

,Age,Number of Dependents,Membership,Satisfaction Score,Tech services,Streaming services,Combined Product,Contract,Tenure in Months,Monthly Charge,Total Revenue,Churn Value
0,78,0,None,3,1,1,2,Month-to-Month,1,39.65,59.65,1
1,74,1,Offer E,3,1,0,1,Month-to-Month,8,80.65,1024.10,1
2,71,3,Offer D,2,0,2,1,Month-to-Month,18,95.45,1910.88,1
3,78,1,Offer C,2,2,2,1,Month-to-Month,25,98.50,2995.07,1
4,80,1,Offer C,2,0,0,1,Month-to-Month,37,76.50,3102.36,1

In [121]:
df = pd.get_dummies(df, columns = ['Membership', 'Contract'])
df

,Age,Number of Dependents,Satisfaction Score,Tech services,Streaming services,Combined Product,Tenure in Months,Monthly Charge,Total Revenue,Churn Value,Membership_None,Membership_Offer A,Membership_Offer B,Membership_Offer C,Membership_Offer D,Membership_Offer E,Contract_Month-to-Month,Contract_One Year,Contract_Two Year
0,78,0,3,1,1,2,1,39.65,59.65,1,1,0,0,0,0,0,1,0,0
1,74,1,3,1,0,1,8,80.65,1024.10,1,0,0,0,0,0,1,1,0,0
2,71,3,2,0,2,1,18,95.45,1910.88,1,0,0,0,0,1,0,1,0,0
3,78,1,2,2,2,1,25,98.50,2995.07,1,0,0,0,1,0,0,1,0,0
4,80,1,2,0,0,1,37,76.50,3102.36,1,0,0,0,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,30,0,5,0,0,4,72,21.15,3039.53,0,1,0,0,0,0,0,0,0,1
7039,38,2,3,3,2,2,24,84.80,2807.47,0,0,0,0,1,0,0,0,1,0
7040,30,2,4,2,2,1,72,103.20,9453.04,0,1,0,0,0,0,0,0,1,0
7041,32,2,4,1,0,2,11,29.60,319.21,0,1,0,0,0,0,0,1,0,0
7042,44,0,4,4,2,1,66,105.65,8887.86,0,1,0,0,0,0,0,0,0,1

In [122]:
from sklearn.model_selection import train_test_split

y_target = df['Churn Value']
X_data = df.drop(['Churn Value'],axis=1,inplace=False)

X_train , X_test , y_train , y_test = train_test_split(X_data , y_target ,test_size=0.2, random_state=156)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((5634, 18), (1409, 18), (5634,), (1409,))

In [123]:
# Initialize variable
X_train_origin, X_test_origin, y_train_origin, y_test_origin = X_train.copy(), X_test.copy(), y_train.copy(), y_test.copy()

In [124]:
from sklearn.preprocessing import MinMaxScaler

# Numeric Only
Numeric_column_list = []
for i in range(len(X_data.columns)):
    if X_data[X_data.columns[i]].dtype == 'float64' or X_data[X_data.columns[i]].dtype == 'int64':
            Numeric_column_list.append(X_data.columns[i])

numeric_train_data, numeric_test_data = X_train[Numeric_column_list], X_test[Numeric_column_list]

scaler = MinMaxScaler()

X_train[Numeric_column_list] = scaler.fit_transform(numeric_train_data)
X_test[Numeric_column_list] = scaler.transform(numeric_test_data)

X_train

,Age,Number of Dependents,Satisfaction Score,Tech services,Streaming services,Combined Product,Tenure in Months,Monthly Charge,Total Revenue,Membership_None,Membership_Offer A,Membership_Offer B,Membership_Offer C,Membership_Offer D,Membership_Offer E,Contract_Month-to-Month,Contract_One Year,Contract_Two Year
1145,0.065574,0.333333,0.50,0.50,1.0,0.000000,0.380282,0.861194,0.264393,0,0,0,1,0,0,1,0,0
86,0.819672,0.000000,0.50,0.00,0.5,0.000000,0.000000,0.606468,0.006514,1,0,0,0,0,0,1,0,0
817,0.918033,0.000000,0.50,1.00,1.0,0.000000,1.000000,0.950746,0.802868,1,0,0,0,0,0,0,0,1
1767,0.557377,0.000000,0.00,0.25,0.0,0.666667,0.239437,0.311443,0.100342,1,0,0,0,0,0,1,0,0
4372,0.377049,0.000000,0.50,1.00,1.0,0.666667,0.915493,0.673134,0.508129,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3082,0.590164,0.000000,0.50,1.00,1.0,0.666667,1.000000,0.733831,0.598247,1,0,0,0,0,0,0,0,1
6955,0.688525,0.111111,0.75,0.00,1.0,0.333333,0.408451,0.261194,0.107580,0,0,0,1,0,0,1,0,0
5695,0.327869,0.000000,0.50,0.50,1.0,0.000000,0.450704,0.888557,0.440201,1,0,0,0,0,0,1,0,0
1442,0.409836,0.000000,0.50,0.00,0.0,1.000000,0.098592,0.014925,0.041201,0,0,0,0,0,1,0,1,0
6860,0.639344,0.000000,0.75,0.50,0.0,0.333333,0.718310,0.171144,0.162033,1,0,0,0,0,0,0,1,0

In [125]:
from sklearn.datasets import make_classification
from sklearn.decomposition import PCA
from imblearn.over_sampling import SMOTE

# 모델설정
sm = SMOTE(sampling_strategy='minority')

# train데이터를 넣어 복제함
X_resampled, y_resampled = sm.fit_resample(X_train, y_train)

print('After OverSampling, the shape of train_X: {}'.format(X_resampled.shape))
print('After OverSampling, the shape of train_y: {} \n'.format(y_resampled.shape))

print("After OverSampling, counts of label '1': {}".format(sum(y_resampled==1)))
print("After OverSampling, counts of label '0': {}".format(sum(y_resampled==0)))

After OverSampling, the shape of train_X: (8262, 18)
After OverSampling, the shape of train_y: (8262,)

After OverSampling, counts of label '1': 4131
After OverSampling, counts of label '0': 4131

In [126]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=0)
X_train_over,y_train_over = smote.fit_resample(X_train, y_train)
print('SMOTE 적용 전 학습용 피처/레이블 데이터 세트: ', X_train.shape, y_train.shape)
print('SMOTE 적용 후 학습용 피처/레이블 데이터 세트: ', X_train_over.shape, y_train_over.shape)
print('SMOTE 적용 후 레이블 값 분포: \n', pd.Series(y_train_over).value_counts())

SMOTE 적용 전 학습용 피처/레이블 데이터 세트:  (5634, 18) (5634,)
SMOTE 적용 후 학습용 피처/레이블 데이터 세트:  (8262, 18) (8262,)
SMOTE 적용 후 레이블 값 분포:
 1    4131
0    4131
Name: Churn Value, dtype: int64

In [127]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score

sgd_model = SGDClassifier(random_state=42)
sgd_model.fit(X_train_over, y_train_over)
y_pred = sgd_model.predict(X_test)

print('정확도:', accuracy_score(y_pred, y_test))
print('f1-score:', f1_score(y_pred, y_test))
print(classification_report(y_test, y_pred))

정확도: 0.9481902058197303
f1-score: 0.8955650929899858
              precision    recall  f1-score   support

           0       0.95      0.98      0.97      1043
           1       0.94      0.86      0.90       366

    accuracy                           0.95      1409
   macro avg       0.95      0.92      0.93      1409
weighted avg       0.95      0.95      0.95      1409

In [128]:
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score

'''
max_iter=10000 : 계산에 사용할 작업 수 
tol=1e-5 : 반복학습이 진행될 때 마다 loss값이 산출 => 이 loss값이 값이 줄어야함. loss값이 tol값보다 작으면 학습중단!
'''

sgd_model_log = SGDClassifier(random_state=88, loss='log', max_iter=10000, tol=0.001) 


sgd_model_log.fit(X_train_over, y_train_over)
y_pred = sgd_model_log.predict(X_test)

print('정확도:', accuracy_score(y_pred, y_test))
print('f1-score:', f1_score(y_pred, y_test))
print(classification_report(y_test, y_pred))

정확도: 0.9382540809084458
f1-score: 0.8874514877102199
              precision    recall  f1-score   support

           0       0.98      0.94      0.96      1043
           1       0.84      0.94      0.89       366

    accuracy                           0.94      1409
   macro avg       0.91      0.94      0.92      1409
weighted avg       0.94      0.94      0.94      1409

In [129]:
#

In [130]:
import pandas as pd

def get_min_max_values_from_excel(excel_file):
    try:
        # 엑셀 파일을 읽어 데이터프레임으로 저장
        df = pd.read_excel(excel_file)
        
        # 컬럼명에서 최솟값과 최댓값 추출
        min_values = []
        max_values = []
        excluded_columns = ["Membership", "Contract", 'Churn Value']  # 제외할 컬럼 목록

        for column in df.columns:
            if column not in excluded_columns:
                min_value = df[column].min()
                max_value = df[column].max()
                min_values.append(min_value)
                max_values.append(max_value)
        
        return min_values, max_values

    except Exception as e:
        print("오류 발생:", str(e))
        return None

# 엑셀 파일 경로
excel_file = "../Churn.xlsx"

# 최솟값과 최댓값 가져오기
min_values, max_values = get_min_max_values_from_excel(excel_file)

if min_values and max_values:
    for column, min_value, max_value in zip(df.columns, min_values, max_values):
        print(f"컬럼명: {column}, 최솟값: {min_value}, 최댓값: {max_value}")
    print(min_values)
    print(max_values)
else:
    print("데이터를 가져올 수 없습니다.")

컬럼명: Age, 최솟값: 19, 최댓값: 80
컬럼명: Number of Dependents, 최솟값: 0, 최댓값: 9
컬럼명: Satisfaction Score, 최솟값: 1, 최댓값: 5
컬럼명: Tech services, 최솟값: 0, 최댓값: 4
컬럼명: Streaming services, 최솟값: 0, 최댓값: 2
컬럼명: Combined Product, 최솟값: 1, 최댓값: 4
컬럼명: Tenure in Months, 최솟값: 1, 최댓값: 72
컬럼명: Monthly Charge, 최솟값: 18.25, 최댓값: 118.75
컬럼명: Total Revenue, 최솟값: 21.36, 최댓값: 11979.34
[19, 0, 1, 0, 0, 1, 1, 18.25, 21.36]
[80, 9, 5, 4, 2, 4, 72, 118.75, 11979.34]

In [131]:
import numpy as np

# 사용자로부터 입력 받기
input_labels = ["나이", "가족 수", "멤버십 단계_1", "멤버십 단계_2", "멤버십 단계_3", "고객 만족도 점수", "기술서비스 이용 개수",
                "부가서비스 이용 개수", "결합상품 이용 개수", "계약 형태_1", "계약 형태_2", "계약 형태_3", "계약 기간",
                "월 요금", "총 요금"]

input_values = []
for label in input_labels:
    value = float(input(f"{label}를 입력하세요: "))
    input_values.append(value)

# 변환 함수
def transform_and_scale(value, min_val, max_val):
    if value > max_val:
        return (value - max_val) / (max_val - min_val)
    elif value < min_val:
        return (value - min_val) / (max_val - min_val)
    else:
        return (value - min_val) / (max_val - min_val)



# 입력 데이터를 Numpy 배열로 변환
customer_data = np.array([scaled_data + dummy_variables], dtype=np.float32)

# 예측 수행
y_customer_pred = sgd_model_log.predict(customer_data)

# 예측 확률 계산
y_customer_prob = sgd_model_log.predict_proba(customer_data)

# 예측 결과 출력
if y_customer_prob[0][1] >= 0.6:
    print("\n고위험 이탈그룹")
elif y_customer_prob[0][1] >= 0.4:
    print("\n잠재적 이탈그룹")
else:
    print("\n안정그룹")

print("이탈확률:", y_customer_prob[0][1])


# features labels
features_labels = ["Age", "Number of Dependents", "Membership", "Satisfaction Score",
                   "Tech services", "Streaming services", "Combined Product", "Contract",
                   "Tenure in Months", "Monthly Charge", "Total Revenue"]

# 각 feature를 변경하면 '안정그룹'으로 예측 결과가 바뀔 수 있는지 확인
threshold = 0.5  # 예측 결과가 '안정그룹'으로 바뀌는 임계값
for i, label in enumerate(features_labels):
    original_value = input_values[i]
    changed_values = [original_value - 0.1, original_value, original_value + 0.1]
    for changed_value in changed_values:
        input_values[i] = changed_value
        scaled_data = [transform_and_scale(value, min_val, max_val) for value, min_val, max_val in zip(input_values, min_values, max_values)]
        customer_data = np.array([scaled_data], dtype=np.float32)
        y_customer_prob_changed = sgd_model_log.predict_proba(customer_data)
        if y_customer_prob_changed[0][1] < threshold:
            print(f"\nChanging {label} to {changed_value} could make it '안정그룹'")

KeyboardInterrupt: Interrupted by user

In [139]:
import numpy as np
import pandas as pd

# 사용자로부터 입력 받기
input_labels_1 = ["Age", "Number of Dependents", "Satisfaction Score", "Tech services",
                "Streaming services", "Combined Product", "Tenure in Months", "Monthly Charge", "Total Revenue"]
input_labels_2 = ['Membership_None', 'Membership_Offer A', 'Membership_Offer B', 'Membership_Offer C', 'Membership_Offer D', 'Membership_Offer E', 'Contract_Month-to-Month', 'Contract_One Year', 'Contract_Two Year']

input_values = []
for label in input_labels_1:
    value = float(input(f"{label}를 입력하세요: "))
    input_values.append(value)

# '멤버십 단계' 및 '계약 형태'
Membership = input("멤버십 단계 (None, Offer A, Offer B, Offer C, Offer D, Offer E 중 하나)를 입력하세요: ")
Contract = input("계약 형태 (Month-to-Month, One Year, Two Year 중 하나)를 입력하세요: ")

# 더미 변수 생성
membership_dummy = [0, 0, 0, 0, 0, 0]  # None, Offer A, Offer B, Offer C, Offer D, Offer E에 대한 더미 변수
contract_dummy = [0, 0, 0]  # Month-to-Month, One Year, Two Year에 대한 더미 변수

if Membership == "None":
    membership_dummy[0] = 1
elif Membership == "Offer A":
    membership_dummy[1] = 1
elif Membership == "Offer B":
    membership_dummy[2] = 1
elif Membership == "Offer C":
    membership_dummy[3] = 1
elif Membership == "Offer D":
    membership_dummy[4] = 1
elif Membership == "Offer E":
    membership_dummy[5] = 1
    
# 같은 방식으로 Contract에 대한 더미 변수 설정
if Contract == "Month-to-Month":
    contract_dummy[0] = 1
elif Contract == "One Year":
    contract_dummy[1] = 1
elif Contract == "Two Year":
    contract_dummy[2] = 1
    
input_values_2 = input_values+membership_dummy+contract_dummy
input_values_2

from sklearn.preprocessing import MinMaxScaler

# 입력 데이터를 선택
input_labels = input_labels_1 + input_labels_2
input_data = pd.DataFrame([input_values_2], columns=input_labels)

# Min-Max 스케일러 생성
scaler = MinMaxScaler()

# 데이터 스케일링
scaled_data = scaler.fit_transform(input_data)

# 스케일링된 데이터를 DataFrame으로 변환 (선택 사항)
#columns = ["Age", "Number of Dependents", "Satisfaction Score", "Tech services", "Streaming services", "Combined Product", "Tenure in Months", "Monthly Charge", "Total Revenue", 
#          'Membership_None', 'Membership_Offer A', 'Membership_Offer B', 'Membership_Offer C', 'Membership_Offer D', 'Membership_Offer E', 'Contract_Month-to-Month', 'Contract_One Year', 'Contract_Two Year']

scaled_data


# 입력 데이터를 Numpy 배열로 변환
customer_data = np.array([scaled_data], dtype=np.float32)

# 예측 수행
y_customer_pred = sgd_model_log.predict(customer_data)

# 예측 확률 계산
y_customer_prob = sgd_model_log.predict_proba(customer_data)

# 예측 결과 출력
if y_customer_prob[0][1] >= 0.6:
    print("\n고위험 이탈그룹")
elif y_customer_prob[0][1] >= 0.4:
    print("\n잠재적 이탈그룹")
else:
    print("\n안정그룹")

print("이탈확률:", y_customer_prob[0][1])

Age를 입력하세요: 1
Number of Dependents를 입력하세요: 1
Satisfaction Score를 입력하세요: 1
Tech services를 입력하세요: 1
Streaming services를 입력하세요: 1
Combined Product를 입력하세요: 1
Tenure in Months를 입력하세요: 1
Monthly Charge를 입력하세요: 1
Total Revenue를 입력하세요: 1
멤버십 단계 (None, Offer A, Offer B, Offer C, Offer D, Offer E 중 하나)를 입력하세요: None
계약 형태 (Month-to-Month, One Year, Two Year 중 하나)를 입력하세요: Month-to-Month

고위험 이탈그룹
이탈확률: 0.999958958370959

ValueError: X has 9 features, but SGDClassifier is expecting 18 features as input.

In [ ]:
# features labels
features_labels = ["Age", "Number of Dependents", "Membership", "Satisfaction Score",
                   "Tech services", "Streaming services", "Combined Product", "Contract",
                   "Tenure in Months", "Monthly Charge", "Total Revenue"]

# 각 feature를 변경하면 '안정그룹'으로 예측 결과가 바뀔 수 있는지 확인
threshold = 0.5  # 예측 결과가 '안정그룹'으로 바뀌는 임계값
for i, label in enumerate(features_labels):
    original_value = input_values[i]
    changed_values = [original_value - 0.1, original_value, original_value + 0.1]
    for changed_value in changed_values:
        input_values[i] = changed_value
        scaled_data = [transform_and_scale(value, min_val, max_val) for value, min_val, max_val in zip(input_values, min_values, max_values)]
        customer_data = np.array([scaled_data], dtype=np.float32)
        y_customer_prob_changed = sgd_model_log.predict_proba(customer_data)
        if y_customer_prob_changed[0][1] < threshold:
            print(f"\nChanging {label} to {changed_value} could make it '안정그룹'")